### PR TITLE
Upgrade TOML parser

### PR DESCRIPTION
**Pull request by gaborbernat**
Resolves https://github.com/PyO3/maturin-action/issues/294

### CODE REVIEW

**Comment by gaborbernat** [comment]
Can you cut a release as it's blocking me 😆

**Comment by messense** [comment]
Unfortuntely it introduces another error:

> TomlError: Control characters (codes < 0x1f and 0x7f) are not allowed in comments, use \u000d instead at row 15, col 58, pos 349:

https://github.com/PyO3/maturin-action/actions/runs/11375889988/job/31647494850

**Comment by gaborbernat** [comment]
Hmm... I am not impacted by bug, bug, but good to know.

**Comment by gaborbernat** [comment]
@messense looking that error is that a bug in the TOML lib or is that a valid error according to TOML spec 1 and we should fix the TOML file?

**Comment by messense** [comment]
> @messense looking that error is that a bug in the TOML lib or is that a valid error according to TOML spec 1 and we should fix the TOML file?

Seems like a big impact bug: https://github.com/iarna/iarna-toml/issues/33

**Pull request merged**
